/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RemoteControlRouteImport } from './routes/remote-control'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DataAnalysisRouteImport } from './routes/data-analysis'
import { Route as DailyEntryRouteImport } from './routes/daily-entry'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientLoginRouteImport } from './routes/client-login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin.users'
import { Route as SuperAdminSystemRouteImport } from './routes/super-admin.system'
import { Route as SuperAdminStorageRouteImport } from './routes/super-admin.storage'
import { Route as SuperAdminSecurityRouteImport } from './routes/super-admin.security'
import { Route as SuperAdminRolesRouteImport } from './routes/super-admin.roles'
import { Route as SuperAdminIntegrationsRouteImport } from './routes/super-admin.integrations'
import { Route as SuperAdminHealthRouteImport } from './routes/super-admin.health'
import { Route as SuperAdminFeaturesRouteImport } from './routes/super-admin.features'
import { Route as SuperAdminEmailRouteImport } from './routes/super-admin.email'
import { Route as SuperAdminDevToolsRouteImport } from './routes/super-admin.dev-tools'
import { Route as SuperAdminCompaniesRouteImport } from './routes/super-admin.companies'
import { Route as SuperAdminBillingRouteImport } from './routes/super-admin.billing'
import { Route as SuperAdminBackupRouteImport } from './routes/super-admin.backup'
import { Route as SuperAdminAuditLogsRouteImport } from './routes/super-admin.audit-logs'
import { Route as SuperAdminApiRouteImport } from './routes/super-admin.api'
import { Route as SuperAdminAnalyticsRouteImport } from './routes/super-admin.analytics'
import { Route as SuperAdminAiControlRouteImport } from './routes/super-admin.ai-control'
import { Route as AdminWorkQueueRouteImport } from './routes/admin.work-queue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemoteControlRoute = RemoteControlRouteImport.update({
  id: '/remote-control',
  path: '/remote-control',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DataAnalysisRoute = DataAnalysisRouteImport.update({
  id: '/data-analysis',
  path: '/data-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyEntryRoute = DailyEntryRouteImport.update({
  id: '/daily-entry',
  path: '/daily-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client-login',
  path: '/client-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSystemRoute = SuperAdminSystemRouteImport.update({
  id: '/super-admin/system',
  path: '/super-admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminStorageRoute = SuperAdminStorageRouteImport.update({
  id: '/super-admin/storage',
  path: '/super-admin/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminSecurityRoute = SuperAdminSecurityRouteImport.update({
  id: '/super-admin/security',
  path: '/super-admin/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRolesRoute = SuperAdminRolesRouteImport.update({
  id: '/super-admin/roles',
  path: '/super-admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIntegrationsRoute = SuperAdminIntegrationsRouteImport.update({
  id: '/super-admin/integrations',
  path: '/super-admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminHealthRoute = SuperAdminHealthRouteImport.update({
  id: '/super-admin/health',
  path: '/super-admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminFeaturesRoute = SuperAdminFeaturesRouteImport.update({
  id: '/super-admin/features',
  path: '/super-admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminEmailRoute = SuperAdminEmailRouteImport.update({
  id: '/super-admin/email',
  path: '/super-admin/email',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDevToolsRoute = SuperAdminDevToolsRouteImport.update({
  id: '/super-admin/dev-tools',
  path: '/super-admin/dev-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminCompaniesRoute = SuperAdminCompaniesRouteImport.update({
  id: '/super-admin/companies',
  path: '/super-admin/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminBillingRoute = SuperAdminBillingRouteImport.update({
  id: '/super-admin/billing',
  path: '/super-admin/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminBackupRoute = SuperAdminBackupRouteImport.update({
  id: '/super-admin/backup',
  path: '/super-admin/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAuditLogsRoute = SuperAdminAuditLogsRouteImport.update({
  id: '/super-admin/audit-logs',
  path: '/super-admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminApiRoute = SuperAdminApiRouteImport.update({
  id: '/super-admin/api',
  path: '/super-admin/api',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAnalyticsRoute = SuperAdminAnalyticsRouteImport.update({
  id: '/super-admin/analytics',
  path: '/super-admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminAiControlRoute = SuperAdminAiControlRouteImport.update({
  id: '/super-admin/ai-control',
  path: '/super-admin/ai-control',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWorkQueueRoute = AdminWorkQueueRouteImport.update({
  id: '/admin/work-queue',
  path: '/admin/work-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/admin/clients',
  path: '/admin/clients',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/daily-entry': typeof DailyEntryRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/documents': typeof DocumentsRoute
  '/remote-control': typeof RemoteControlRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/work-queue': typeof AdminWorkQueueRoute
  '/super-admin/ai-control': typeof SuperAdminAiControlRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/api': typeof SuperAdminApiRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/dev-tools': typeof SuperAdminDevToolsRoute
  '/super-admin/email': typeof SuperAdminEmailRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/integrations': typeof SuperAdminIntegrationsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/storage': typeof SuperAdminStorageRoute
  '/super-admin/system': typeof SuperAdminSystemRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/daily-entry': typeof DailyEntryRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/documents': typeof DocumentsRoute
  '/remote-control': typeof RemoteControlRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/work-queue': typeof AdminWorkQueueRoute
  '/super-admin/ai-control': typeof SuperAdminAiControlRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/api': typeof SuperAdminApiRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/dev-tools': typeof SuperAdminDevToolsRoute
  '/super-admin/email': typeof SuperAdminEmailRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/integrations': typeof SuperAdminIntegrationsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/storage': typeof SuperAdminStorageRoute
  '/super-admin/system': typeof SuperAdminSystemRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/client-login': typeof ClientLoginRoute
  '/contact': typeof ContactRoute
  '/daily-entry': typeof DailyEntryRoute
  '/data-analysis': typeof DataAnalysisRoute
  '/documents': typeof DocumentsRoute
  '/remote-control': typeof RemoteControlRoute
  '/settings': typeof SettingsRoute
  '/support': typeof SupportRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/work-queue': typeof AdminWorkQueueRoute
  '/super-admin/ai-control': typeof SuperAdminAiControlRoute
  '/super-admin/analytics': typeof SuperAdminAnalyticsRoute
  '/super-admin/api': typeof SuperAdminApiRoute
  '/super-admin/audit-logs': typeof SuperAdminAuditLogsRoute
  '/super-admin/backup': typeof SuperAdminBackupRoute
  '/super-admin/billing': typeof SuperAdminBillingRoute
  '/super-admin/companies': typeof SuperAdminCompaniesRoute
  '/super-admin/dev-tools': typeof SuperAdminDevToolsRoute
  '/super-admin/email': typeof SuperAdminEmailRoute
  '/super-admin/features': typeof SuperAdminFeaturesRoute
  '/super-admin/health': typeof SuperAdminHealthRoute
  '/super-admin/integrations': typeof SuperAdminIntegrationsRoute
  '/super-admin/roles': typeof SuperAdminRolesRoute
  '/super-admin/security': typeof SuperAdminSecurityRoute
  '/super-admin/storage': typeof SuperAdminStorageRoute
  '/super-admin/system': typeof SuperAdminSystemRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/client-login'
    | '/contact'
    | '/daily-entry'
    | '/data-analysis'
    | '/documents'
    | '/remote-control'
    | '/settings'
    | '/support'
    | '/admin/clients'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/work-queue'
    | '/super-admin/ai-control'
    | '/super-admin/analytics'
    | '/super-admin/api'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/dev-tools'
    | '/super-admin/email'
    | '/super-admin/features'
    | '/super-admin/health'
    | '/super-admin/integrations'
    | '/super-admin/roles'
    | '/super-admin/security'
    | '/super-admin/storage'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/client-login'
    | '/contact'
    | '/daily-entry'
    | '/data-analysis'
    | '/documents'
    | '/remote-control'
    | '/settings'
    | '/support'
    | '/admin/clients'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/work-queue'
    | '/super-admin/ai-control'
    | '/super-admin/analytics'
    | '/super-admin/api'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/dev-tools'
    | '/super-admin/email'
    | '/super-admin/features'
    | '/super-admin/health'
    | '/super-admin/integrations'
    | '/super-admin/roles'
    | '/super-admin/security'
    | '/super-admin/storage'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/client-login'
    | '/contact'
    | '/daily-entry'
    | '/data-analysis'
    | '/documents'
    | '/remote-control'
    | '/settings'
    | '/support'
    | '/admin/clients'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/work-queue'
    | '/super-admin/ai-control'
    | '/super-admin/analytics'
    | '/super-admin/api'
    | '/super-admin/audit-logs'
    | '/super-admin/backup'
    | '/super-admin/billing'
    | '/super-admin/companies'
    | '/super-admin/dev-tools'
    | '/super-admin/email'
    | '/super-admin/features'
    | '/super-admin/health'
    | '/super-admin/integrations'
    | '/super-admin/roles'
    | '/super-admin/security'
    | '/super-admin/storage'
    | '/super-admin/system'
    | '/super-admin/users'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ContactRoute: typeof ContactRoute
  DailyEntryRoute: typeof DailyEntryRoute
  DataAnalysisRoute: typeof DataAnalysisRoute
  DocumentsRoute: typeof DocumentsRoute
  RemoteControlRoute: typeof RemoteControlRoute
  SettingsRoute: typeof SettingsRoute
  SupportRoute: typeof SupportRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminWorkQueueRoute: typeof AdminWorkQueueRoute
  SuperAdminAiControlRoute: typeof SuperAdminAiControlRoute
  SuperAdminAnalyticsRoute: typeof SuperAdminAnalyticsRoute
  SuperAdminApiRoute: typeof SuperAdminApiRoute
  SuperAdminAuditLogsRoute: typeof SuperAdminAuditLogsRoute
  SuperAdminBackupRoute: typeof SuperAdminBackupRoute
  SuperAdminBillingRoute: typeof SuperAdminBillingRoute
  SuperAdminCompaniesRoute: typeof SuperAdminCompaniesRoute
  SuperAdminDevToolsRoute: typeof SuperAdminDevToolsRoute
  SuperAdminEmailRoute: typeof SuperAdminEmailRoute
  SuperAdminFeaturesRoute: typeof SuperAdminFeaturesRoute
  SuperAdminHealthRoute: typeof SuperAdminHealthRoute
  SuperAdminIntegrationsRoute: typeof SuperAdminIntegrationsRoute
  SuperAdminRolesRoute: typeof SuperAdminRolesRoute
  SuperAdminSecurityRoute: typeof SuperAdminSecurityRoute
  SuperAdminStorageRoute: typeof SuperAdminStorageRoute
  SuperAdminSystemRoute: typeof SuperAdminSystemRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remote-control': {
      id: '/remote-control'
      path: '/remote-control'
      fullPath: '/remote-control'
      preLoaderRoute: typeof RemoteControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-analysis': {
      id: '/data-analysis'
      path: '/data-analysis'
      fullPath: '/data-analysis'
      preLoaderRoute: typeof DataAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-entry': {
      id: '/daily-entry'
      path: '/daily-entry'
      fullPath: '/daily-entry'
      preLoaderRoute: typeof DailyEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-login': {
      id: '/client-login'
      path: '/client-login'
      fullPath: '/client-login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/system': {
      id: '/super-admin/system'
      path: '/super-admin/system'
      fullPath: '/super-admin/system'
      preLoaderRoute: typeof SuperAdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/storage': {
      id: '/super-admin/storage'
      path: '/super-admin/storage'
      fullPath: '/super-admin/storage'
      preLoaderRoute: typeof SuperAdminStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/security': {
      id: '/super-admin/security'
      path: '/super-admin/security'
      fullPath: '/super-admin/security'
      preLoaderRoute: typeof SuperAdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/roles': {
      id: '/super-admin/roles'
      path: '/super-admin/roles'
      fullPath: '/super-admin/roles'
      preLoaderRoute: typeof SuperAdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/integrations': {
      id: '/super-admin/integrations'
      path: '/super-admin/integrations'
      fullPath: '/super-admin/integrations'
      preLoaderRoute: typeof SuperAdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/health': {
      id: '/super-admin/health'
      path: '/super-admin/health'
      fullPath: '/super-admin/health'
      preLoaderRoute: typeof SuperAdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/features': {
      id: '/super-admin/features'
      path: '/super-admin/features'
      fullPath: '/super-admin/features'
      preLoaderRoute: typeof SuperAdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/email': {
      id: '/super-admin/email'
      path: '/super-admin/email'
      fullPath: '/super-admin/email'
      preLoaderRoute: typeof SuperAdminEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dev-tools': {
      id: '/super-admin/dev-tools'
      path: '/super-admin/dev-tools'
      fullPath: '/super-admin/dev-tools'
      preLoaderRoute: typeof SuperAdminDevToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/companies': {
      id: '/super-admin/companies'
      path: '/super-admin/companies'
      fullPath: '/super-admin/companies'
      preLoaderRoute: typeof SuperAdminCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/billing': {
      id: '/super-admin/billing'
      path: '/super-admin/billing'
      fullPath: '/super-admin/billing'
      preLoaderRoute: typeof SuperAdminBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/backup': {
      id: '/super-admin/backup'
      path: '/super-admin/backup'
      fullPath: '/super-admin/backup'
      preLoaderRoute: typeof SuperAdminBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/audit-logs': {
      id: '/super-admin/audit-logs'
      path: '/super-admin/audit-logs'
      fullPath: '/super-admin/audit-logs'
      preLoaderRoute: typeof SuperAdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/api': {
      id: '/super-admin/api'
      path: '/super-admin/api'
      fullPath: '/super-admin/api'
      preLoaderRoute: typeof SuperAdminApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/analytics': {
      id: '/super-admin/analytics'
      path: '/super-admin/analytics'
      fullPath: '/super-admin/analytics'
      preLoaderRoute: typeof SuperAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/ai-control': {
      id: '/super-admin/ai-control'
      path: '/super-admin/ai-control'
      fullPath: '/super-admin/ai-control'
      preLoaderRoute: typeof SuperAdminAiControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/work-queue': {
      id: '/admin/work-queue'
      path: '/admin/work-queue'
      fullPath: '/admin/work-queue'
      preLoaderRoute: typeof AdminWorkQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/admin/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ClientLoginRoute: ClientLoginRoute,
  ContactRoute: ContactRoute,
  DailyEntryRoute: DailyEntryRoute,
  DataAnalysisRoute: DataAnalysisRoute,
  DocumentsRoute: DocumentsRoute,
  RemoteControlRoute: RemoteControlRoute,
  SettingsRoute: SettingsRoute,
  SupportRoute: SupportRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminWorkQueueRoute: AdminWorkQueueRoute,
  SuperAdminAiControlRoute: SuperAdminAiControlRoute,
  SuperAdminAnalyticsRoute: SuperAdminAnalyticsRoute,
  SuperAdminApiRoute: SuperAdminApiRoute,
  SuperAdminAuditLogsRoute: SuperAdminAuditLogsRoute,
  SuperAdminBackupRoute: SuperAdminBackupRoute,
  SuperAdminBillingRoute: SuperAdminBillingRoute,
  SuperAdminCompaniesRoute: SuperAdminCompaniesRoute,
  SuperAdminDevToolsRoute: SuperAdminDevToolsRoute,
  SuperAdminEmailRoute: SuperAdminEmailRoute,
  SuperAdminFeaturesRoute: SuperAdminFeaturesRoute,
  SuperAdminHealthRoute: SuperAdminHealthRoute,
  SuperAdminIntegrationsRoute: SuperAdminIntegrationsRoute,
  SuperAdminRolesRoute: SuperAdminRolesRoute,
  SuperAdminSecurityRoute: SuperAdminSecurityRoute,
  SuperAdminStorageRoute: SuperAdminStorageRoute,
  SuperAdminSystemRoute: SuperAdminSystemRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
